apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-5
  namespace: argocd
spec:
  destination: 
    namespace: default
    server: https://kubernetes.default.svc
  project: project-5
  source:
    path: v03-argocd-applications/helm/nginx
    repoURL: https://github.com/ghkimdev/argocd-tutorial.git
    targetRevision: main


