apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-6
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: 'Namespace'
  namespaceResourceBlacklist:
  - group: 'apps'
    kind: 'Deployment'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
