apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-8
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
    - name: read-only
      description: "this role can be used for reading applications for example"
      policies: 
        - p, proj:project-7:read-only, applications, get, project-7/*, allow

