apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-post-job-success
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: mattermost-success
          image: mattermost:final
          command: [ "python3", "mattermost_api.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync OK ***"
          - name: url
            value: "localhost"
          - name: token
            value: "1ey5hrwqkpy5uecsjjfbhs4cur"
          - name: scheme
            value: "http"
          - name: port
            value: "8080"
          - name: channel_name
            value: "argocd-course"
          - name: team_name
            value: "mattermost"
      restartPolicy: Never
  backoffLimit: 0
